
version: 2

sources:
  - name: nyc_taxi
    schema: dtc_nyc_trip_data
    tables:
      - name: rides
  - name: nyc_taxi_partition
    schema: 'dtc_nyc_trip_data.INFORMATION_SCHEMA'
    tables:
      - name: PARTITIONS